<?php

namespace App\Http\Requests;

use Illuminate\Contracts\Validation\ValidationRule;
use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Validation\Rule;

class UpdateTenantNavigationRequest extends FormRequest
{
    public function authorize(): bool
    {
        $tenant = app('currentTenant');

        return $this->user()?->id === $tenant->user_id;
    }

    /**
     * @return array<string, ValidationRule|array<mixed>|string>
     */
    public function rules(): array
    {
        $hex = 'regex:/^#[0-9A-Fa-f]{6}$/';

        return [
            'navigation_config' => ['required', 'array'],
            'navigation_config.header' => ['required', 'array'],
            'navigation_config.header.variant' => ['sometimes', 'string', Rule::in([
                ...array_keys(config('navigation.navbar_variants')),
                ...config('navigation.legacy_navbar_variants'),
            ])],
            'navigation_config.header.menu' => ['sometimes', 'array'],
            'navigation_config.header.menu.mode' => ['sometimes', Rule::in(['simple', 'mega'])],
            'navigation_config.header.menu.triggerLabel' => ['sometimes', 'string', 'max:40'],
            'navigation_config.header.menu.openOn' => ['sometimes', Rule::in(['click', 'hover'])],
            'navigation_config.header.menu.alignment' => ['sometimes', Rule::in(['left', 'center', 'right'])],
            'navigation_config.header.menu.width' => ['sometimes', Rule::in(['content', 'wide', 'full'])],
            'navigation_config.header.menu.columns' => ['sometimes', 'integer', Rule::in([2, 3, 4])],
            'navigation_config.header.menu.animation' => ['sometimes', Rule::in(['fade', 'slide', 'scale'])],
            'navigation_config.header.menu.groups' => ['sometimes', 'array', 'list', 'max:4'],
            'navigation_config.header.menu.groups.*.id' => ['required', 'string', 'max:80', 'distinct'],
            'navigation_config.header.menu.groups.*.label' => ['required', 'string', 'max:40'],
            'navigation_config.header.menu.groups.*.description' => ['nullable', 'string', 'max:120'],
            'navigation_config.header.menu.featured' => ['sometimes', 'array'],
            'navigation_config.header.menu.featured.show' => ['sometimes', 'boolean'],
            'navigation_config.header.menu.featured.title' => ['nullable', 'string', 'max:60'],
            'navigation_config.header.menu.featured.description' => ['nullable', 'string', 'max:160'],
            'navigation_config.header.menu.featured.imageUrl' => ['nullable', 'string', 'max:2048'],
            'navigation_config.header.menu.featured.href' => ['nullable', 'url', 'max:2048'],
            'navigation_config.header.surface' => ['sometimes', 'array'],
            'navigation_config.header.surface.mode' => ['sometimes', Rule::in(array_keys(config('navigation.navbar_surface_modes')))],
            'navigation_config.header.surface.backgroundColor' => ['required_if:navigation_config.header.surface.mode,custom', 'string', $hex],
            'navigation_config.header.surface.textColor' => ['required_if:navigation_config.header.surface.mode,custom', 'string', $hex],
            'navigation_config.header.brand' => ['sometimes', 'array'],
            'navigation_config.header.brand.type' => ['sometimes', Rule::in(['text', 'image'])],
            'navigation_config.header.brand.text' => ['nullable', 'string', 'max:60'],
            'navigation_config.header.brand.imageUrl' => ['nullable', 'string', 'max:2048'],
            'navigation_config.header.brand.alt' => ['nullable', 'string', 'max:100'],
            'navigation_config.header.brand.width' => ['sometimes', 'integer', 'between:40,280'],
            'navigation_config.header.brand.mobileWidth' => ['sometimes', 'integer', 'between:32,220'],
            'navigation_config.header.brand.hideOnMobile' => ['sometimes', 'boolean'],
            'navigation_config.header.layout' => ['sometimes', 'array'],
            'navigation_config.header.layout.contentWidth' => ['sometimes', 'integer', 'between:720,1800'],
            'navigation_config.header.layout.height' => ['sometimes', 'integer', 'between:48,140'],
            'navigation_config.header.layout.horizontalPadding' => ['sometimes', 'integer', 'between:0,96'],
            'navigation_config.header.layout.position' => ['sometimes', Rule::in(['static', 'sticky'])],
            'navigation_config.header.layout.stickyOffset' => ['sometimes', 'integer', 'between:0,160'],
            'navigation_config.header.layout.fullWidth' => ['sometimes', 'boolean'],
            'navigation_config.header.layout.borderWidth' => ['sometimes', 'integer', 'between:0,6'],
            'navigation_config.header.layout.borderColor' => ['sometimes', 'string', $hex],
            'navigation_config.header.layout.borderRadius' => ['sometimes', 'integer', 'between:0,80'],
            'navigation_config.header.layout.shadow' => ['sometimes', Rule::in(['none', 'small', 'medium', 'large'])],
            'navigation_config.header.responsive' => ['sometimes', 'array'],
            'navigation_config.header.responsive.breakpoint' => ['sometimes', 'integer', 'between:480,1024'],
            'navigation_config.header.responsive.menuStyle' => ['sometimes', Rule::in(['dropdown', 'drawer', 'fullscreen'])],
            'navigation_config.header.responsive.menuIcon' => ['sometimes', Rule::in(['menu', 'dots', 'grid'])],
            'navigation_config.header.responsive.alignment' => ['sometimes', Rule::in(['left', 'center'])],
            'navigation_config.header.responsive.showActions' => ['sometimes', 'boolean'],
            'navigation_config.header.states' => ['sometimes', 'array'],
            'navigation_config.header.states.activeColor' => ['sometimes', 'string', $hex],
            'navigation_config.header.states.focusColor' => ['sometimes', 'string', $hex],
            'navigation_config.header.states.disabledOpacity' => ['sometimes', 'integer', 'between:20,70'],
            'navigation_config.header.states.scrolledBackgroundColor' => ['sometimes', 'string', $hex],
            'navigation_config.header.states.scrolledTextColor' => ['sometimes', 'string', $hex],
            'navigation_config.header.actionPosition' => ['sometimes', Rule::in(['start', 'end'])],
            'navigation_config.header.actionStyle' => ['sometimes', 'array'],
            'navigation_config.header.actionStyle.mode' => ['sometimes', Rule::in(['theme', 'custom'])],
            'navigation_config.header.actionStyle.backgroundColor' => ['required_if:navigation_config.header.actionStyle.mode,custom', 'string', $hex],
            'navigation_config.header.actionStyle.textColor' => ['required_if:navigation_config.header.actionStyle.mode,custom', 'string', $hex],
            'navigation_config.header.actionStyle.hoverBackgroundColor' => ['required_if:navigation_config.header.actionStyle.mode,custom', 'string', $hex],
            'navigation_config.header.actionStyle.hoverTextColor' => ['required_if:navigation_config.header.actionStyle.mode,custom', 'string', $hex],
            'navigation_config.header.linkStyle' => ['sometimes', 'array'],
            'navigation_config.header.linkStyle.mode' => ['sometimes', Rule::in(['theme', 'custom'])],
            'navigation_config.header.linkStyle.color' => ['required_if:navigation_config.header.linkStyle.mode,custom', 'string', $hex],
            'navigation_config.header.linkStyle.hoverColor' => ['required_if:navigation_config.header.linkStyle.mode,custom', 'string', $hex],
            'navigation_config.header.linkStyle.hoverEffect' => ['sometimes', Rule::in(['color', 'underline', 'background', 'lift', 'none'])],
            'navigation_config.header.items' => ['sometimes', 'array', 'list', 'max:12'],
            'navigation_config.header.items.*.id' => ['nullable', 'string', 'max:80', 'distinct'],
            'navigation_config.header.items.*.label' => ['required', 'string', 'max:40'],
            'navigation_config.header.items.*.type' => ['sometimes', Rule::in(['internal', 'external'])],
            'navigation_config.header.items.*.slug' => ['nullable', 'string', 'max:255'],
            'navigation_config.header.items.*.href' => ['nullable', 'url', 'max:2048'],
            'navigation_config.header.items.*.disabled' => ['sometimes', 'boolean'],
            'navigation_config.header.items.*.megaGroup' => ['nullable', 'string', 'max:80'],
            'navigation_config.header.items.*.children' => ['sometimes', 'array', 'list', 'max:8'],
            'navigation_config.header.items.*.children.*.id' => ['nullable', 'string', 'max:80'],
            'navigation_config.header.items.*.children.*.label' => ['required', 'string', 'max:40'],
            'navigation_config.header.items.*.children.*.type' => ['sometimes', Rule::in(['internal', 'external'])],
            'navigation_config.header.items.*.children.*.slug' => ['nullable', 'string', 'max:255'],
            'navigation_config.header.items.*.children.*.href' => ['nullable', 'url', 'max:2048'],
            'navigation_config.header.actions' => ['sometimes', 'array', 'list', 'max:3'],
            'navigation_config.header.actions.*.id' => ['nullable', 'string', 'max:80', 'distinct'],
            'navigation_config.header.actions.*.label' => ['required', 'string', 'max:40'],
            'navigation_config.header.actions.*.type' => ['required', Rule::in(['internal', 'external'])],
            'navigation_config.header.actions.*.slug' => ['nullable', 'string', 'max:255'],
            'navigation_config.header.actions.*.href' => ['nullable', 'url', 'max:2048'],
            'navigation_config.header.actions.*.disabled' => ['sometimes', 'boolean'],
            'navigation_config.header.actions.*.variant' => ['required', Rule::in(['primary', 'outline', 'text'])],
            'navigation_config.header.actions.*.icon' => ['sometimes', Rule::in(['none', 'arrow', 'bag'])],
            'navigation_config.header.actions.*.iconPosition' => ['sometimes', Rule::in(['start', 'end'])],
            'navigation_config.header.actions.*.size' => ['sometimes', Rule::in(['small', 'medium', 'large'])],
            'navigation_config.header.actions.*.animation' => ['sometimes', Rule::in(['color', 'lift', 'scale', 'arrow', 'none'])],
            'navigation_config.header.actions.*.backgroundColor' => ['nullable', 'string', $hex],
            'navigation_config.header.actions.*.textColor' => ['nullable', 'string', $hex],
            'navigation_config.header.actions.*.hoverBackgroundColor' => ['nullable', 'string', $hex],
            'navigation_config.header.actions.*.hoverTextColor' => ['nullable', 'string', $hex],
            'navigation_config.header.actions.*.borderColor' => ['nullable', 'string', $hex],
            'navigation_config.header.actions.*.borderRadius' => ['sometimes', 'integer', 'between:0,40'],
            'navigation_config.header.search' => ['sometimes', 'array'],
            'navigation_config.header.search.show' => ['sometimes', 'boolean'],
            'navigation_config.header.search.placeholder' => ['nullable', 'string', 'max:60'],
            'navigation_config.header.showLogo' => ['sometimes', 'boolean'],
            'navigation_config.header.ctaButton' => ['sometimes', 'array'],
            'navigation_config.header.ctaButton.show' => ['sometimes', 'boolean'],
            'navigation_config.header.ctaButton.label' => ['nullable', 'string', 'max:40'],
            'navigation_config.header.ctaButton.slug' => ['nullable', 'string', 'max:255'],
            'navigation_config.footer' => ['required', 'array'],
            'navigation_config.footer.variant' => ['sometimes', Rule::in(array_keys(config('navigation.footer_variants')))],
            'navigation_config.footer.moduleOrder' => ['sometimes', 'array', 'list', 'max:5'],
            'navigation_config.footer.moduleOrder.*' => ['required', 'string', 'distinct', Rule::in(['brand', 'links', 'newsletter', 'social', 'copyright'])],
            'navigation_config.footer.backgroundMode' => ['sometimes', Rule::in(['theme', 'contrast', 'custom'])],
            'navigation_config.footer.backgroundColor' => ['required_if:navigation_config.footer.backgroundMode,custom', 'string', $hex],
            'navigation_config.footer.textColor' => ['required_if:navigation_config.footer.backgroundMode,custom', 'string', $hex],
            'navigation_config.footer.contentWidth' => ['sometimes', 'integer', 'between:720,1800'],
            'navigation_config.footer.showLinks' => ['sometimes', 'boolean'],
            'navigation_config.footer.showSocial' => ['sometimes', 'boolean'],
            'navigation_config.footer.showCopyright' => ['sometimes', 'boolean'],
            'navigation_config.footer.brand' => ['sometimes', 'array'],
            'navigation_config.footer.brand.show' => ['sometimes', 'boolean'],
            'navigation_config.footer.brand.title' => ['nullable', 'string', 'max:80'],
            'navigation_config.footer.brand.description' => ['nullable', 'string', 'max:280'],
            'navigation_config.footer.brand.imageUrl' => ['nullable', 'string', 'max:2048'],
            'navigation_config.footer.brand.alt' => ['nullable', 'string', 'max:120'],
            'navigation_config.footer.linkGroups' => ['sometimes', 'array', 'list', 'max:6'],
            'navigation_config.footer.linkGroups.*.id' => ['required', 'string', 'max:80', 'distinct'],
            'navigation_config.footer.linkGroups.*.label' => ['required', 'string', 'max:60'],
            'navigation_config.footer.linkGroups.*.links' => ['required', 'array', 'list', 'max:10'],
            'navigation_config.footer.linkGroups.*.links.*.id' => ['nullable', 'string', 'max:80'],
            'navigation_config.footer.linkGroups.*.links.*.label' => ['required', 'string', 'max:60'],
            'navigation_config.footer.linkGroups.*.links.*.type' => ['sometimes', Rule::in(['internal', 'external'])],
            'navigation_config.footer.linkGroups.*.links.*.slug' => ['nullable', 'string', 'max:255'],
            'navigation_config.footer.linkGroups.*.links.*.href' => ['nullable', 'url', 'max:2048'],
            'navigation_config.footer.newsletter' => ['sometimes', 'array'],
            'navigation_config.footer.newsletter.show' => ['sometimes', 'boolean'],
            'navigation_config.footer.newsletter.eyebrow' => ['nullable', 'string', 'max:60'],
            'navigation_config.footer.newsletter.heading' => ['nullable', 'string', 'max:120'],
            'navigation_config.footer.newsletter.body' => ['nullable', 'string', 'max:280'],
            'navigation_config.footer.newsletter.buttonLabel' => ['nullable', 'string', 'max:60'],
            'navigation_config.footer.newsletter.buttonUrl' => ['nullable', 'string', 'max:2048'],
            'navigation_config.footer.socialLinks' => ['sometimes', 'array', 'list', 'max:8'],
            'navigation_config.footer.socialLinks.*.id' => ['required', 'string', 'max:80', 'distinct'],
            'navigation_config.footer.socialLinks.*.label' => ['required', 'string', 'max:40'],
            'navigation_config.footer.socialLinks.*.href' => ['required', 'url', 'max:2048'],
            'navigation_config.footer.copyright' => ['nullable', 'string', 'max:255'],
            'navigation_config.presets' => ['sometimes', 'array', 'list', 'max:10'],
            'navigation_config.presets.*.id' => ['required', 'string', 'max:80', 'distinct'],
            'navigation_config.presets.*.name' => ['required', 'string', 'max:60'],
            'navigation_config.presets.*.header' => ['required', 'array'],
            'navigation_config.commerce' => ['sometimes', 'array'],
        ];
    }
}
