<?php

return [
    'definitions' => [
        'HeroBlock' => [
            'type' => 'HeroBlock',
            'label' => 'Hero Section',
            'category' => 'content',
            'icon' => 'layout',
            'defaultProps' => [
                'padding' => 40,
                'backgroundColor' => 'transparent',
                'headline' => 'Welcome to your Site',
                'subheadline' => 'Built with our engine.',
            ],
            'inspectorFields' => [
                ['key' => 'padding', 'label' => 'Padding (px)', 'type' => 'range', 'min' => 10, 'max' => 150],
                ['key' => 'backgroundColor', 'label' => 'Background Color', 'type' => 'color'],
                ['key' => 'headline', 'label' => 'Headline Text', 'type' => 'text', 'placeholder' => 'Enter headline'],
                ['key' => 'subheadline', 'label' => 'Subheadline Text', 'type' => 'text', 'placeholder' => 'Enter subheadline'],
            ],
        ],
        'FeatureBlock' => [
            'type' => 'FeatureBlock',
            'label' => 'Feature Block',
            'category' => 'content',
            'icon' => 'star',
            'defaultProps' => [
                'padding' => 20,
                'backgroundColor' => 'transparent',
                'title' => 'Feature Item',
                'body' => 'Feature description details go here.',
            ],
            'inspectorFields' => [
                ['key' => 'padding', 'label' => 'Padding (px)', 'type' => 'range', 'min' => 10, 'max' => 150],
                ['key' => 'backgroundColor', 'label' => 'Background Color', 'type' => 'color'],
                ['key' => 'title', 'label' => 'Feature Title', 'type' => 'text', 'placeholder' => 'Enter title'],
                ['key' => 'body', 'label' => 'Feature Body', 'type' => 'text', 'placeholder' => 'Enter description'],
            ],
        ],
        'AtomicText' => [
            'type' => 'AtomicText',
            'label' => 'Atomic Text',
            'category' => 'content',
            'icon' => 'type',
            'defaultProps' => [
                'padding' => 20,
                'backgroundColor' => 'transparent',
                'content' => 'Atomic Text Element',
                'fontSize' => '16px',
                'color' => '#0f172a',
            ],
            'inspectorFields' => [
                ['key' => 'padding', 'label' => 'Padding (px)', 'type' => 'range', 'min' => 10, 'max' => 150],
                ['key' => 'backgroundColor', 'label' => 'Background Color', 'type' => 'color'],
                ['key' => 'content', 'label' => 'Text Content', 'type' => 'text', 'placeholder' => 'Enter text'],
                ['key' => 'fontSize', 'label' => 'Font Size (e.g. 16px, 1.25rem)', 'type' => 'text'],
                ['key' => 'color', 'label' => 'Text Color', 'type' => 'text'],
            ],
        ],
        'LayoutGrid' => [
            'type' => 'LayoutGrid',
            'label' => 'Layout Grid',
            'category' => 'layout',
            'icon' => 'grid',
            'defaultProps' => [
                'padding' => 20,
                'backgroundColor' => 'transparent',
                'columns' => 3,
                'gap' => '1rem',
            ],
            'inspectorFields' => [
                ['key' => 'padding', 'label' => 'Padding (px)', 'type' => 'range', 'min' => 10, 'max' => 150],
                ['key' => 'backgroundColor', 'label' => 'Background Color', 'type' => 'color'],
                ['key' => 'columns', 'label' => 'Columns Count', 'type' => 'number', 'min' => 1, 'max' => 12],
                ['key' => 'gap', 'label' => 'Gap Size (e.g. 1rem, 16px)', 'type' => 'text'],
            ],
            'allowedChildren' => [
                'HeroBlock', 'FeatureBlock', 'LayoutGrid', 'LayoutColumn', 'AtomicText', 'ButtonBlock', 'DividerBlock', 'SpacerBlock', 'ImageBlock',
                'RichTextBlock', 'VideoEmbedBlock', 'FAQBlock', 'TestimonialBlock', 'PricingTableBlock', 'ContactFormBlock',
            ],
        ],
        'LayoutColumn' => [
            'type' => 'LayoutColumn',
            'label' => 'Layout Column',
            'category' => 'layout',
            'icon' => 'columns',
            'defaultProps' => [
                'padding' => 20,
                'backgroundColor' => 'transparent',
                'span' => 'auto',
                'width' => 'auto',
                'height' => 'auto',
                'gap' => '0px',
            ],
            'inspectorFields' => [
                ['key' => 'padding', 'label' => 'Padding (px)', 'type' => 'range', 'min' => 10, 'max' => 150],
                ['key' => 'backgroundColor', 'label' => 'Background Color', 'type' => 'color'],
                ['key' => 'span', 'label' => 'Grid Column Span (1-12) or Flex Basis', 'type' => 'text'],
                ['key' => 'width', 'label' => 'Width (e.g. auto, 100%)', 'type' => 'text'],
                ['key' => 'height', 'label' => 'Height (e.g. auto, 200px)', 'type' => 'text'],
                ['key' => 'gap', 'label' => 'Gap', 'type' => 'text'],
            ],
            'allowedChildren' => [
                'HeroBlock', 'FeatureBlock', 'LayoutGrid', 'LayoutColumn', 'AtomicText', 'ButtonBlock', 'DividerBlock', 'SpacerBlock', 'ImageBlock',
                'RichTextBlock', 'VideoEmbedBlock', 'FAQBlock', 'TestimonialBlock', 'PricingTableBlock', 'ContactFormBlock',
            ],
        ],
        'ButtonBlock' => [
            'type' => 'ButtonBlock',
            'label' => 'Button',
            'category' => 'content',
            'icon' => 'link',
            'defaultProps' => [
                'label' => 'Click Me',
                'variant' => 'primary',
                'url' => '',
                'size' => 'md',
            ],
            'inspectorFields' => [
                ['key' => 'label', 'label' => 'Button Text', 'type' => 'text', 'placeholder' => 'Enter button text'],
                ['key' => 'variant', 'label' => 'Variant', 'type' => 'text'],
                ['key' => 'url', 'label' => 'Link URL', 'type' => 'text', 'placeholder' => 'https://...'],
                ['key' => 'size', 'label' => 'Size', 'type' => 'text'],
            ],
        ],
        'DividerBlock' => [
            'type' => 'DividerBlock',
            'label' => 'Divider',
            'category' => 'content',
            'icon' => 'minus',
            'defaultProps' => [
                'thickness' => 1,
                'color' => '#cbd5e1',
                'margin' => 16,
            ],
            'inspectorFields' => [
                ['key' => 'thickness', 'label' => 'Thickness (px)', 'type' => 'range', 'min' => 1, 'max' => 8],
                ['key' => 'color', 'label' => 'Color', 'type' => 'color'],
                ['key' => 'margin', 'label' => 'Margin (px)', 'type' => 'range', 'min' => 0, 'max' => 60],
            ],
        ],
        'SpacerBlock' => [
            'type' => 'SpacerBlock',
            'label' => 'Spacer',
            'category' => 'content',
            'icon' => 'vertical',
            'defaultProps' => [
                'height' => 24,
            ],
            'inspectorFields' => [
                ['key' => 'height', 'label' => 'Height (px)', 'type' => 'range', 'min' => 4, 'max' => 200],
            ],
        ],
        'ImageBlock' => [
            'type' => 'ImageBlock',
            'label' => 'Image',
            'category' => 'media',
            'icon' => 'image',
            'defaultProps' => [
                'src' => '',
                'alt' => '',
                'objectFit' => 'cover',
                'borderRadius' => 'var(--theme-border-radius)',
                'width' => '100%',
                'height' => '300px',
                'padding' => 0,
                'backgroundColor' => 'transparent',
            ],
            'inspectorFields' => [
                ['key' => 'src',          'label' => 'Image',           'type' => 'media'],
                ['key' => 'alt',          'label' => 'Alt Text',         'type' => 'text', 'placeholder' => 'Describe the image...'],
                ['key' => 'objectFit',    'label' => 'Object Fit',       'type' => 'select', 'options' => [
                    ['label' => 'Cover',   'value' => 'cover'],
                    ['label' => 'Contain', 'value' => 'contain'],
                    ['label' => 'Fill',    'value' => 'fill'],
                ]],
                ['key' => 'width',        'label' => 'Width',            'type' => 'text'],
                ['key' => 'height',       'label' => 'Height',           'type' => 'text'],
                ['key' => 'borderRadius', 'label' => 'Border Radius',    'type' => 'text'],
                ['key' => 'padding',      'label' => 'Padding (px)',     'type' => 'range', 'min' => 0, 'max' => 100],
                ['key' => 'backgroundColor', 'label' => 'Background',   'type' => 'color'],
            ],
        ],
        'RichTextBlock' => [
            'type' => 'RichTextBlock',
            'label' => 'Rich Text',
            'category' => 'content',
            'icon' => 'file-text',
            'defaultProps' => [
                'html' => '<p>Start typing...</p>',
                'padding' => 20,
                'backgroundColor' => 'transparent',
            ],
            'inspectorFields' => [
                ['key' => 'padding', 'label' => 'Padding (px)', 'type' => 'range', 'min' => 0, 'max' => 150],
                ['key' => 'backgroundColor', 'label' => 'Background Color', 'type' => 'color'],
            ],
        ],
        'VideoEmbedBlock' => [
            'type' => 'VideoEmbedBlock',
            'label' => 'Video Embed',
            'category' => 'media',
            'icon' => 'video',
            'defaultProps' => [
                'url' => '',
                'provider' => 'youtube',
                'aspectRatio' => '16/9',
                'padding' => 20,
                'backgroundColor' => 'transparent',
            ],
            'inspectorFields' => [
                ['key' => 'url', 'label' => 'Video URL', 'type' => 'text', 'placeholder' => 'YouTube, Vimeo, or Loom URL'],
                ['key' => 'provider', 'label' => 'Provider', 'type' => 'select', 'options' => [
                    ['label' => 'YouTube', 'value' => 'youtube'],
                    ['label' => 'Vimeo', 'value' => 'vimeo'],
                    ['label' => 'Loom', 'value' => 'loom'],
                    ['label' => 'Direct / Raw', 'value' => 'raw'],
                ]],
                ['key' => 'aspectRatio', 'label' => 'Aspect Ratio', 'type' => 'select', 'options' => [
                    ['label' => '16:9', 'value' => '16/9'],
                    ['label' => '4:3', 'value' => '4/3'],
                    ['label' => '1:1', 'value' => '1/1'],
                ]],
                ['key' => 'padding', 'label' => 'Padding (px)', 'type' => 'range', 'min' => 0, 'max' => 150],
                ['key' => 'backgroundColor', 'label' => 'Background Color', 'type' => 'color'],
            ],
        ],
        'FAQBlock' => [
            'type' => 'FAQBlock',
            'label' => 'FAQ Accordion',
            'category' => 'content',
            'icon' => 'help-circle',
            'defaultProps' => [
                'items' => [
                    ['question' => 'What is this platform?', 'answer' => 'It is a multitenant website builder.'],
                    ['question' => 'How does pricing work?', 'answer' => 'Check our plans section below.'],
                ],
                'padding' => 20,
                'backgroundColor' => 'transparent',
            ],
            'inspectorFields' => [
                ['key' => 'items', 'label' => 'FAQ Items', 'type' => 'repeater', 'subFields' => [
                    ['key' => 'question', 'label' => 'Question', 'type' => 'text', 'placeholder' => 'Enter question'],
                    ['key' => 'answer', 'label' => 'Answer', 'type' => 'text', 'placeholder' => 'Enter answer'],
                ]],
                ['key' => 'padding', 'label' => 'Padding (px)', 'type' => 'range', 'min' => 0, 'max' => 150],
                ['key' => 'backgroundColor', 'label' => 'Background Color', 'type' => 'color'],
            ],
        ],
        'TestimonialBlock' => [
            'type' => 'TestimonialBlock',
            'label' => 'Testimonial',
            'category' => 'content',
            'icon' => 'message-square',
            'defaultProps' => [
                'quote' => 'This website builder is incredibly fast and customizable!',
                'authorName' => 'Jane Smith',
                'authorRole' => 'CEO, TechCorp',
                'avatarSrc' => '',
                'padding' => 40,
                'backgroundColor' => 'transparent',
            ],
            'inspectorFields' => [
                ['key' => 'quote', 'label' => 'Quote Text', 'type' => 'text', 'placeholder' => 'Enter testimonial quote'],
                ['key' => 'authorName', 'label' => 'Author Name', 'type' => 'text', 'placeholder' => 'Enter name'],
                ['key' => 'authorRole', 'label' => 'Author Role / Company', 'type' => 'text', 'placeholder' => 'Enter role'],
                ['key' => 'avatarSrc', 'label' => 'Avatar Image', 'type' => 'media'],
                ['key' => 'padding', 'label' => 'Padding (px)', 'type' => 'range', 'min' => 0, 'max' => 150],
                ['key' => 'backgroundColor', 'label' => 'Background Color', 'type' => 'color'],
            ],
        ],
        'PricingTableBlock' => [
            'type' => 'PricingTableBlock',
            'label' => 'Pricing Cards',
            'category' => 'content',
            'icon' => 'dollar-sign',
            'defaultProps' => [
                'plans' => [
                    [
                        'title' => 'Starter',
                        'price' => '$9',
                        'period' => '/mo',
                        'features' => '1 Website, 5GB Storage, Community Support',
                        'ctaText' => 'Get Started',
                        'ctaUrl' => '#',
                        'isPopular' => false,
                    ],
                    [
                        'title' => 'Professional',
                        'price' => '$29',
                        'period' => '/mo',
                        'features' => '5 Websites, 50GB Storage, Priority Support',
                        'ctaText' => 'Upgrade Now',
                        'ctaUrl' => '#',
                        'isPopular' => true,
                    ],
                ],
                'padding' => 40,
                'backgroundColor' => 'transparent',
            ],
            'inspectorFields' => [
                ['key' => 'plans', 'label' => 'Pricing Plans', 'type' => 'repeater', 'subFields' => [
                    ['key' => 'title', 'label' => 'Plan Title', 'type' => 'text'],
                    ['key' => 'price', 'label' => 'Price (e.g. $29)', 'type' => 'text'],
                    ['key' => 'period', 'label' => 'Period (e.g. /mo)', 'type' => 'text'],
                    ['key' => 'features', 'label' => 'Features (comma-separated)', 'type' => 'text'],
                    ['key' => 'ctaText', 'label' => 'Button Label', 'type' => 'text'],
                    ['key' => 'ctaUrl', 'label' => 'Button Link', 'type' => 'text'],
                    ['key' => 'isPopular', 'label' => 'Popular / Highlighted', 'type' => 'select', 'options' => [
                        ['label' => 'No', 'value' => 'no'],
                        ['label' => 'Yes', 'value' => 'yes'],
                    ]],
                ]],
                ['key' => 'padding', 'label' => 'Padding (px)', 'type' => 'range', 'min' => 0, 'max' => 150],
                ['key' => 'backgroundColor', 'label' => 'Background Color', 'type' => 'color'],
            ],
        ],
        'ContactFormBlock' => [
            'type' => 'ContactFormBlock',
            'label' => 'Contact Form',
            'category' => 'content',
            'icon' => 'mail',
            'defaultProps' => [
                'fields' => [
                    ['type' => 'text', 'label' => 'Your Name', 'placeholder' => 'John Doe', 'required' => 'yes'],
                    ['type' => 'email', 'label' => 'Your Email', 'placeholder' => 'john@example.com', 'required' => 'yes'],
                    ['type' => 'textarea', 'label' => 'Message', 'placeholder' => 'How can we help?', 'required' => 'yes'],
                ],
                'submitLabel' => 'Send Message',
                'successMessage' => 'Thank you! Your message has been sent successfully.',
                'padding' => 40,
                'backgroundColor' => 'transparent',
            ],
            'inspectorFields' => [
                ['key' => 'submitLabel', 'label' => 'Submit Button Text', 'type' => 'text'],
                ['key' => 'successMessage', 'label' => 'Success Message', 'type' => 'text'],
                ['key' => 'fields', 'label' => 'Form Fields', 'type' => 'repeater', 'subFields' => [
                    ['key' => 'type', 'label' => 'Field Type', 'type' => 'select', 'options' => [
                        ['label' => 'Text', 'value' => 'text'],
                        ['label' => 'Email', 'value' => 'email'],
                        ['label' => 'Textarea', 'value' => 'textarea'],
                    ]],
                    ['key' => 'label', 'label' => 'Label', 'type' => 'text'],
                    ['key' => 'placeholder', 'label' => 'Placeholder', 'type' => 'text'],
                    ['key' => 'required', 'label' => 'Required', 'type' => 'select', 'options' => [
                        ['label' => 'Yes', 'value' => 'yes'],
                        ['label' => 'No', 'value' => 'no'],
                    ]],
                ]],
                ['key' => 'padding', 'label' => 'Padding (px)', 'type' => 'range', 'min' => 0, 'max' => 150],
                ['key' => 'backgroundColor', 'label' => 'Background Color', 'type' => 'color'],
            ],
        ],
    ],
    'nesting' => [
        'LayoutGrid' => [
            'HeroBlock', 'FeatureBlock', 'LayoutGrid', 'LayoutColumn', 'AtomicText', 'ButtonBlock', 'DividerBlock', 'SpacerBlock', 'ImageBlock',
            'RichTextBlock', 'VideoEmbedBlock', 'FAQBlock', 'TestimonialBlock', 'PricingTableBlock', 'ContactFormBlock',
        ],
        'LayoutColumn' => [
            'HeroBlock', 'FeatureBlock', 'LayoutGrid', 'LayoutColumn', 'AtomicText', 'ButtonBlock', 'DividerBlock', 'SpacerBlock', 'ImageBlock',
            'RichTextBlock', 'VideoEmbedBlock', 'FAQBlock', 'TestimonialBlock', 'PricingTableBlock', 'ContactFormBlock',
        ],
    ],
];
