<?php

return [
    'definitions' => [
        'SectionBlock' => [
            'type' => 'SectionBlock',
            'label' => 'Section',
            'category' => 'layout',
            'icon' => 'panels-top-left',
            'defaultProps' => [
                'patternKey' => 'hero-centered',
                'padding' => 0,
                'sectionPadding' => 72,
                'backgroundColor' => 'transparent',
                'backgroundImage' => '',
                'contentWidth' => 1180,
                'minHeight' => 520,
                'verticalAlign' => 'center',
                'textAlign' => 'left',
                'overlayOpacity' => 0,
            ],
            'inspectorFields' => [
                ['key' => 'sectionPadding', 'label' => 'Section Padding (px)', 'type' => 'range', 'min' => 24, 'max' => 160, 'group' => 'style'],
                ['key' => 'contentWidth', 'label' => 'Content Width (px)', 'type' => 'number', 'min' => 640, 'max' => 1600, 'group' => 'style'],
                ['key' => 'minHeight', 'label' => 'Minimum Height (px)', 'type' => 'range', 'min' => 240, 'max' => 900, 'group' => 'style'],
                ['key' => 'verticalAlign', 'label' => 'Vertical Alignment', 'type' => 'segmented', 'group' => 'style', 'options' => [
                    ['label' => 'Top', 'value' => 'start'],
                    ['label' => 'Center', 'value' => 'center'],
                    ['label' => 'Bottom', 'value' => 'end'],
                ]],
                ['key' => 'textAlign', 'label' => 'Text Alignment', 'type' => 'segmented', 'group' => 'style', 'options' => [
                    ['label' => 'Left', 'value' => 'left'],
                    ['label' => 'Center', 'value' => 'center'],
                    ['label' => 'Right', 'value' => 'right'],
                ]],
                ['key' => 'backgroundColor', 'label' => 'Background Color', 'type' => 'theme-color', 'group' => 'style', 'compact' => true, 'allowTransparent' => true, 'defaultValue' => 'transparent', 'customDefault' => '#f4f4f5'],
                ['key' => 'backgroundImage', 'label' => 'Background Image', 'type' => 'media', 'group' => 'style'],
                ['key' => 'overlayOpacity', 'label' => 'Image Overlay (%)', 'type' => 'range', 'min' => 0, 'max' => 80, 'group' => 'style'],
            ],
            'allowedChildren' => [
                'HeroBlock', 'FeatureBlock', 'LayoutGrid', 'LayoutColumn', 'AtomicText', 'ButtonBlock', 'DividerBlock', 'SpacerBlock', 'ImageBlock',
                'RichTextBlock', 'VideoEmbedBlock', 'FAQBlock', 'TestimonialBlock', 'PricingTableBlock', 'ContactFormBlock',
                'AnnouncementBlock', 'ImageWithTextBlock', 'CollectionListBlock', 'ProductGridBlock', 'ProductDetailBlock', 'CartBlock', 'NewsletterBlock', 'TrustValuesBlock', 'MenuBlock',
            ],
        ],
        'HeroBlock' => [
            'type' => 'HeroBlock',
            'label' => 'Hero Section',
            'category' => 'content',
            'icon' => 'layout',
            'defaultProps' => [
                'padding' => 40,
                'backgroundColor' => 'transparent',
                'headline' => 'Welcome to your Site',
                'subheadline' => 'Built with our engine.',
                'fontFamily' => 'heading',
                'headlineColor' => '--theme-text',
                'subheadlineColor' => '',
                'align' => 'center',
            ],
            'inspectorFields' => [
                ['key' => 'headline', 'label' => 'Headline Text', 'type' => 'text', 'placeholder' => 'Enter headline'],
                ['key' => 'subheadline', 'label' => 'Subheadline Text', 'type' => 'text', 'placeholder' => 'Enter subheadline'],
                ['key' => 'padding', 'label' => 'Padding (px)', 'type' => 'range', 'min' => 10, 'max' => 150, 'group' => 'style'],
                ['key' => 'backgroundColor', 'label' => 'Background Color', 'type' => 'theme-color', 'group' => 'style', 'compact' => true, 'allowTransparent' => true, 'defaultValue' => 'transparent', 'customDefault' => '#f4f4f5'],
                ['key' => 'fontFamily', 'label' => 'Headline Font', 'type' => 'segmented', 'group' => 'style', 'options' => [
                    ['label' => 'Heading', 'value' => 'heading'],
                    ['label' => 'Body', 'value' => 'body'],
                ]],
                ['key' => 'headlineColor', 'label' => 'Headline Color', 'type' => 'theme-color', 'group' => 'style', 'compact' => true, 'defaultValue' => '--theme-text'],
                ['key' => 'subheadlineColor', 'label' => 'Subheadline Color', 'type' => 'theme-color', 'group' => 'style', 'compact' => true, 'defaultValue' => '--theme-text'],
                ['key' => 'align', 'label' => 'Alignment', 'type' => 'segmented', 'group' => 'style', 'options' => [
                    ['label' => 'Left', 'value' => 'left'],
                    ['label' => 'Center', 'value' => 'center'],
                    ['label' => 'Right', 'value' => 'right'],
                ]],
            ],
        ],
        'FeatureBlock' => [
            'type' => 'FeatureBlock',
            'label' => 'Feature Block',
            'category' => 'content',
            'icon' => 'star',
            'defaultProps' => [
                'padding' => 20,
                'backgroundColor' => 'transparent',
                'title' => 'Feature Item',
                'body' => 'Feature description details go here.',
                'fontFamily' => 'heading',
                'titleColor' => '--theme-text',
                'bodyColor' => '',
            ],
            'inspectorFields' => [
                ['key' => 'title', 'label' => 'Feature Title', 'type' => 'text', 'placeholder' => 'Enter title'],
                ['key' => 'body', 'label' => 'Feature Body', 'type' => 'textarea', 'placeholder' => 'Enter description'],
                ['key' => 'padding', 'label' => 'Padding (px)', 'type' => 'range', 'min' => 10, 'max' => 150, 'group' => 'style'],
                ['key' => 'backgroundColor', 'label' => 'Background Color', 'type' => 'theme-color', 'group' => 'style', 'compact' => true, 'allowTransparent' => true, 'defaultValue' => 'transparent', 'customDefault' => '#f4f4f5'],
                ['key' => 'fontFamily', 'label' => 'Title Font', 'type' => 'segmented', 'group' => 'style', 'options' => [
                    ['label' => 'Heading', 'value' => 'heading'],
                    ['label' => 'Body', 'value' => 'body'],
                ]],
                ['key' => 'titleColor', 'label' => 'Title Color', 'type' => 'theme-color', 'group' => 'style', 'compact' => true, 'defaultValue' => '--theme-text'],
                ['key' => 'bodyColor', 'label' => 'Body Color', 'type' => 'theme-color', 'group' => 'style', 'compact' => true, 'defaultValue' => '--theme-text'],
            ],
        ],
        'AtomicText' => [
            'type' => 'AtomicText',
            'label' => 'Atomic Text',
            'category' => 'content',
            'icon' => 'type',
            'defaultProps' => [
                'padding' => 20,
                'backgroundColor' => 'transparent',
                'content' => 'Atomic Text Element',
                'fontSize' => '16px',
                'color' => '--theme-text',
                'fontFamily' => 'body',
                'fontWeight' => '400',
                'lineHeight' => '1.4',
                'letterSpacing' => '0em',
                'textAlign' => 'inherit',
                'maxWidth' => 'none',
            ],
            'inspectorFields' => [
                ['key' => 'content', 'label' => 'Text Content', 'type' => 'textarea', 'placeholder' => 'Enter text'],
                ['key' => 'fontSize', 'label' => 'Font Size', 'type' => 'font-size', 'group' => 'style'],
                ['key' => 'color', 'label' => 'Text Color', 'type' => 'theme-color', 'group' => 'style', 'compact' => true, 'defaultValue' => '--theme-text'],
                ['key' => 'fontFamily', 'label' => 'Font Family', 'type' => 'segmented', 'group' => 'style', 'options' => [
                    ['label' => 'Body', 'value' => 'body'],
                    ['label' => 'Heading', 'value' => 'heading'],
                ]],
                ['key' => 'fontWeight', 'label' => 'Font Weight', 'type' => 'select', 'group' => 'style', 'options' => [
                    ['label' => 'Regular', 'value' => '400'],
                    ['label' => 'Medium', 'value' => '500'],
                    ['label' => 'Semibold', 'value' => '600'],
                    ['label' => 'Bold', 'value' => '700'],
                    ['label' => 'Extra bold', 'value' => '800'],
                ]],
                ['key' => 'lineHeight', 'label' => 'Line Height', 'type' => 'select', 'group' => 'style', 'options' => [
                    ['label' => 'Tight (1.2)', 'value' => '1.2'],
                    ['label' => 'Normal (1.4)', 'value' => '1.4'],
                    ['label' => 'Relaxed (1.6)', 'value' => '1.6'],
                    ['label' => 'Loose (2.0)', 'value' => '2.0'],
                ]],
                ['key' => 'letterSpacing', 'label' => 'Letter Spacing', 'type' => 'select', 'group' => 'style', 'options' => [
                    ['label' => 'Normal (0em)', 'value' => '0em'],
                    ['label' => 'Wide (0.05em)', 'value' => '0.05em'],
                    ['label' => 'Widest (0.1em)', 'value' => '0.1em'],
                ]],
                ['key' => 'textAlign', 'label' => 'Text Alignment', 'type' => 'segmented', 'group' => 'style', 'options' => [
                    ['label' => 'Auto', 'value' => 'inherit'],
                    ['label' => 'Left', 'value' => 'left'],
                    ['label' => 'Center', 'value' => 'center'],
                    ['label' => 'Right', 'value' => 'right'],
                ]],
                ['key' => 'maxWidth', 'label' => 'Maximum Width', 'type' => 'select', 'group' => 'style', 'options' => [
                    ['label' => 'Full container width', 'value' => 'none'],
                    ['label' => 'Narrow (480px)', 'value' => '480px'],
                    ['label' => 'Prose (680px)', 'value' => '680px'],
                    ['label' => 'Wide (960px)', 'value' => '960px'],
                ]],
                ['key' => 'padding', 'label' => 'Padding (px)', 'type' => 'range', 'min' => 10, 'max' => 150, 'group' => 'style'],
                ['key' => 'backgroundColor', 'label' => 'Background Color', 'type' => 'theme-color', 'group' => 'style', 'compact' => true, 'allowTransparent' => true, 'defaultValue' => 'transparent', 'customDefault' => '#f4f4f5'],
            ],
        ],
        'LayoutGrid' => [
            'type' => 'LayoutGrid',
            'label' => 'Layout Grid',
            'category' => 'layout',
            'icon' => 'grid',
            'defaultProps' => [
                'padding' => 20,
                'backgroundColor' => 'transparent',
                'columns' => 3,
                'gap' => '1rem',
                'columnTemplate' => 'equal',
                'alignItems' => 'stretch',
                'stackOnNarrow' => true,
            ],
            'inspectorFields' => [
                ['key' => 'columns', 'label' => 'Columns', 'type' => 'columns', 'group' => 'style', 'options' => [
                    ['label' => '1', 'value' => 1],
                    ['label' => '2', 'value' => 2],
                    ['label' => '3', 'value' => 3],
                    ['label' => '4', 'value' => 4],
                    ['label' => '6', 'value' => 6],
                ]],
                ['key' => 'columnTemplate', 'label' => 'Column Proportions', 'type' => 'segmented', 'group' => 'style', 'options' => [
                    ['label' => 'Equal', 'value' => 'equal'],
                    ['label' => 'Wide left', 'value' => 'wide-left'],
                    ['label' => 'Wide right', 'value' => 'wide-right'],
                ]],
                ['key' => 'gap', 'label' => 'Gap Size', 'type' => 'select', 'group' => 'style', 'options' => [
                    ['label' => 'None (0px)', 'value' => '0px'],
                    ['label' => 'Small (12px)', 'value' => '12px'],
                    ['label' => 'Medium (16px)', 'value' => '1rem'],
                    ['label' => 'Large (24px)', 'value' => '24px'],
                    ['label' => 'Extra Large (40px)', 'value' => '40px'],
                ]],
                ['key' => 'alignItems', 'label' => 'Vertical Alignment', 'type' => 'segmented', 'group' => 'style', 'options' => [
                    ['label' => 'Stretch', 'value' => 'stretch'],
                    ['label' => 'Top', 'value' => 'start'],
                    ['label' => 'Center', 'value' => 'center'],
                    ['label' => 'Bottom', 'value' => 'end'],
                ]],
                ['key' => 'stackOnNarrow', 'label' => 'Stack on mobile', 'type' => 'toggle', 'group' => 'style'],
                ['key' => 'padding', 'label' => 'Padding (px)', 'type' => 'range', 'min' => 10, 'max' => 150, 'group' => 'style'],
                ['key' => 'backgroundColor', 'label' => 'Background Color', 'type' => 'theme-color', 'group' => 'style', 'compact' => true, 'allowTransparent' => true, 'defaultValue' => 'transparent', 'customDefault' => '#f4f4f5'],
            ],
            'allowedChildren' => [
                'HeroBlock', 'FeatureBlock', 'LayoutGrid', 'LayoutColumn', 'AtomicText', 'ButtonBlock', 'DividerBlock', 'SpacerBlock', 'ImageBlock',
                'RichTextBlock', 'VideoEmbedBlock', 'FAQBlock', 'TestimonialBlock', 'PricingTableBlock', 'ContactFormBlock',
                'AnnouncementBlock', 'ImageWithTextBlock', 'CollectionListBlock', 'ProductGridBlock', 'ProductDetailBlock', 'CartBlock', 'NewsletterBlock', 'TrustValuesBlock', 'MenuBlock',
            ],
        ],
        'LayoutColumn' => [
            'type' => 'LayoutColumn',
            'label' => 'Layout Column',
            'category' => 'layout',
            'icon' => 'columns',
            'defaultProps' => [
                'padding' => 20,
                'backgroundColor' => 'transparent',
                'span' => 'auto',
                'width' => 'auto',
                'height' => 'auto',
                'gap' => '16px',
                'verticalAlign' => 'start',
                'horizontalAlign' => 'stretch',
            ],
            'inspectorFields' => [
                ['key' => 'span', 'label' => 'Grid Column Span', 'type' => 'select', 'group' => 'style', 'options' => [
                    ['label' => 'Auto', 'value' => 'auto'],
                    ['label' => '1 Column', 'value' => '1'],
                    ['label' => '2 Columns', 'value' => '2'],
                    ['label' => '3 Columns', 'value' => '3'],
                    ['label' => '4 Columns', 'value' => '4'],
                    ['label' => '6 Columns', 'value' => '6'],
                    ['label' => '8 Columns', 'value' => '8'],
                    ['label' => '12 Columns', 'value' => '12'],
                ]],
                ['key' => 'width', 'label' => 'Width (e.g. auto, 100%)', 'type' => 'text', 'group' => 'style'],
                ['key' => 'height', 'label' => 'Height (e.g. auto, 200px)', 'type' => 'text', 'group' => 'style'],
                ['key' => 'gap', 'label' => 'Gap Size', 'type' => 'select', 'group' => 'style', 'options' => [
                    ['label' => 'None (0px)', 'value' => '0px'],
                    ['label' => 'Small (12px)', 'value' => '12px'],
                    ['label' => 'Medium (16px)', 'value' => '16px'],
                    ['label' => 'Large (24px)', 'value' => '24px'],
                ]],
                ['key' => 'verticalAlign', 'label' => 'Vertical Alignment', 'type' => 'segmented', 'group' => 'style', 'options' => [
                    ['label' => 'Top', 'value' => 'start'],
                    ['label' => 'Center', 'value' => 'center'],
                    ['label' => 'Bottom', 'value' => 'end'],
                    ['label' => 'Between', 'value' => 'space-between'],
                ]],
                ['key' => 'horizontalAlign', 'label' => 'Horizontal Alignment', 'type' => 'segmented', 'group' => 'style', 'options' => [
                    ['label' => 'Stretch', 'value' => 'stretch'],
                    ['label' => 'Left', 'value' => 'start'],
                    ['label' => 'Center', 'value' => 'center'],
                    ['label' => 'Right', 'value' => 'end'],
                ]],
                ['key' => 'padding', 'label' => 'Padding (px)', 'type' => 'range', 'min' => 10, 'max' => 150, 'group' => 'style'],
                ['key' => 'backgroundColor', 'label' => 'Background Color', 'type' => 'theme-color', 'group' => 'style', 'compact' => true, 'allowTransparent' => true, 'defaultValue' => 'transparent', 'customDefault' => '#f4f4f5'],
            ],
            'allowedChildren' => [
                'HeroBlock', 'FeatureBlock', 'LayoutGrid', 'LayoutColumn', 'AtomicText', 'ButtonBlock', 'DividerBlock', 'SpacerBlock', 'ImageBlock',
                'RichTextBlock', 'VideoEmbedBlock', 'FAQBlock', 'TestimonialBlock', 'PricingTableBlock', 'ContactFormBlock',
                'AnnouncementBlock', 'ImageWithTextBlock', 'CollectionListBlock', 'ProductGridBlock', 'ProductDetailBlock', 'CartBlock', 'NewsletterBlock', 'TrustValuesBlock', 'MenuBlock',
            ],
        ],
        'ButtonBlock' => [
            'type' => 'ButtonBlock',
            'label' => 'Button',
            'category' => 'content',
            'icon' => 'link',
            'defaultProps' => [
                'label' => 'Click Me',
                'variant' => 'primary',
                'url' => '',
                'openInNewTab' => false,
                'size' => 'md',
                'alignment' => 'center',
                'borderRadius' => '',
                'backgroundColor' => '',
                'textColor' => '',
                'hoverBackgroundColor' => '',
                'hoverTextColor' => '',
            ],
            'inspectorFields' => [
                ['key' => 'label', 'label' => 'Button Text', 'type' => 'text', 'placeholder' => 'Enter button text'],
                ['key' => 'url', 'label' => 'Link URL', 'type' => 'text', 'placeholder' => 'https://... or /about'],
                ['key' => 'openInNewTab', 'label' => 'Open link in new tab', 'type' => 'toggle'],
                ['key' => 'variant', 'label' => 'Style preset', 'type' => 'segmented', 'group' => 'style', 'options' => [
                    ['label' => 'Primary', 'value' => 'primary'],
                    ['label' => 'Secondary', 'value' => 'secondary'],
                    ['label' => 'Outline', 'value' => 'outline'],
                ]],
                ['key' => 'size', 'label' => 'Size', 'type' => 'segmented', 'group' => 'style', 'options' => [
                    ['label' => 'Small', 'value' => 'sm'],
                    ['label' => 'Medium', 'value' => 'md'],
                    ['label' => 'Large', 'value' => 'lg'],
                ]],
                ['key' => 'alignment', 'label' => 'Alignment', 'type' => 'segmented', 'group' => 'style', 'options' => [
                    ['label' => 'Left', 'value' => 'start'],
                    ['label' => 'Center', 'value' => 'center'],
                    ['label' => 'Right', 'value' => 'end'],
                ]],
                ['key' => 'borderRadius', 'label' => 'Corners', 'type' => 'select', 'group' => 'style', 'options' => [
                    ['label' => 'Theme default', 'value' => ''],
                    ['label' => 'Square', 'value' => '0px'],
                    ['label' => 'Soft', 'value' => '8px'],
                    ['label' => 'Rounded', 'value' => '16px'],
                    ['label' => 'Pill', 'value' => '9999px'],
                ]],
                ['key' => 'textColor', 'label' => 'Text / outline color', 'type' => 'theme-color', 'group' => 'style', 'compact' => true, 'clearable' => true, 'clearLabel' => 'Use preset', 'defaultValue' => '--theme-primary', 'customDefault' => '#4f46e5'],
                ['key' => 'backgroundColor', 'label' => 'Background color', 'type' => 'theme-color', 'group' => 'style', 'compact' => true, 'clearable' => true, 'clearLabel' => 'Use preset', 'allowTransparent' => true, 'defaultValue' => '--theme-primary', 'customDefault' => '#4f46e5'],
                ['key' => 'hoverBackgroundColor', 'label' => 'Hover background', 'type' => 'theme-color', 'group' => 'style', 'compact' => true, 'clearable' => true, 'clearLabel' => 'Use preset', 'allowTransparent' => true, 'defaultValue' => '--theme-secondary', 'customDefault' => '#0ea5e9'],
                ['key' => 'hoverTextColor', 'label' => 'Hover text color', 'type' => 'theme-color', 'group' => 'style', 'compact' => true, 'clearable' => true, 'clearLabel' => 'Use preset', 'defaultValue' => '#ffffff', 'customDefault' => '#ffffff'],
            ],
        ],
        'DividerBlock' => [
            'type' => 'DividerBlock',
            'label' => 'Divider',
            'category' => 'content',
            'icon' => 'minus',
            'defaultProps' => [
                'thickness' => 1,
                'color' => '#cbd5e1',
                'margin' => 16,
            ],
            'inspectorFields' => [
                ['key' => 'thickness', 'label' => 'Thickness (px)', 'type' => 'range', 'min' => 1, 'max' => 8, 'group' => 'style'],
                ['key' => 'color', 'label' => 'Color', 'type' => 'theme-color', 'group' => 'style', 'compact' => true, 'defaultValue' => '#cbd5e1', 'customDefault' => '#cbd5e1'],
                ['key' => 'margin', 'label' => 'Margin (px)', 'type' => 'range', 'min' => 0, 'max' => 60, 'group' => 'style'],
            ],
        ],
        'SpacerBlock' => [
            'type' => 'SpacerBlock',
            'label' => 'Spacer',
            'category' => 'content',
            'icon' => 'vertical',
            'defaultProps' => [
                'height' => 24,
            ],
            'inspectorFields' => [
                ['key' => 'height', 'label' => 'Height (px)', 'type' => 'range', 'min' => 4, 'max' => 200, 'group' => 'style'],
            ],
        ],
        'ImageBlock' => [
            'type' => 'ImageBlock',
            'label' => 'Image',
            'category' => 'media',
            'icon' => 'image',
            'defaultProps' => [
                'src' => '',
                'alt' => '',
                'objectFit' => 'cover',
                'borderRadius' => 'var(--theme-border-radius)',
                'width' => '100%',
                'height' => '300px',
                'padding' => 0,
                'backgroundColor' => 'transparent',
            ],
            'inspectorFields' => [
                ['key' => 'src',          'label' => 'Image',           'type' => 'media'],
                ['key' => 'alt',          'label' => 'Alt Text',         'type' => 'text', 'placeholder' => 'Describe the image...'],
                ['key' => 'objectFit',    'label' => 'Object Fit',       'type' => 'segmented', 'group' => 'style', 'options' => [
                    ['label' => 'Cover',   'value' => 'cover'],
                    ['label' => 'Contain', 'value' => 'contain'],
                    ['label' => 'Fill',    'value' => 'fill'],
                ]],
                ['key' => 'width',        'label' => 'Width',            'type' => 'select', 'group' => 'style', 'options' => [
                    ['label' => 'Full width (100%)', 'value' => '100%'],
                    ['label' => 'Auto',              'value' => 'auto'],
                    ['label' => 'Half width (50%)',  'value' => '50%'],
                ]],
                ['key' => 'height',       'label' => 'Height',           'type' => 'select', 'group' => 'style', 'options' => [
                    ['label' => 'Medium (300px)', 'value' => '300px'],
                    ['label' => 'Small (200px)',  'value' => '200px'],
                    ['label' => 'Large (450px)',  'value' => '450px'],
                    ['label' => 'Auto height',    'value' => 'auto'],
                ]],
                ['key' => 'borderRadius', 'label' => 'Border Radius',    'type' => 'select', 'group' => 'style', 'options' => [
                    ['label' => 'Theme default',             'value' => 'var(--theme-border-radius)'],
                    ['label' => 'None (0px)',                'value' => '0px'],
                    ['label' => 'Small (4px)',               'value' => '4px'],
                    ['label' => 'Medium (8px)',              'value' => '8px'],
                    ['label' => 'Large (16px)',              'value' => '16px'],
                    ['label' => 'Pill / Round (9999px)',     'value' => '9999px'],
                ]],
                ['key' => 'padding',      'label' => 'Padding (px)',     'type' => 'range', 'min' => 0, 'max' => 100, 'group' => 'style'],
                ['key' => 'backgroundColor', 'label' => 'Background',   'type' => 'theme-color', 'group' => 'style', 'compact' => true, 'allowTransparent' => true, 'defaultValue' => 'transparent', 'customDefault' => '#f4f4f5'],
            ],
        ],
        'RichTextBlock' => [
            'type' => 'RichTextBlock',
            'label' => 'Rich Text',
            'category' => 'content',
            'icon' => 'file-text',
            'defaultProps' => [
                'html' => '<p>Start typing...</p>',
                'padding' => 20,
                'backgroundColor' => 'transparent',
            ],
            'inspectorFields' => [
                ['key' => 'padding', 'label' => 'Padding (px)', 'type' => 'range', 'min' => 0, 'max' => 150, 'group' => 'style'],
                ['key' => 'backgroundColor', 'label' => 'Background Color', 'type' => 'theme-color', 'group' => 'style', 'compact' => true, 'allowTransparent' => true, 'defaultValue' => 'transparent', 'customDefault' => '#f4f4f5'],
            ],
        ],
        'VideoEmbedBlock' => [
            'type' => 'VideoEmbedBlock',
            'label' => 'Video Embed',
            'category' => 'media',
            'icon' => 'video',
            'defaultProps' => [
                'url' => '',
                'provider' => 'youtube',
                'aspectRatio' => '16/9',
                'posterUrl' => '',
                'padding' => 20,
                'backgroundColor' => 'transparent',
            ],
            'inspectorFields' => [
                ['key' => 'url', 'label' => 'Video URL', 'type' => 'text', 'placeholder' => 'YouTube, Vimeo, or Loom URL'],
                ['key' => 'provider', 'label' => 'Provider', 'type' => 'select', 'options' => [
                    ['label' => 'YouTube', 'value' => 'youtube'],
                    ['label' => 'Vimeo', 'value' => 'vimeo'],
                    ['label' => 'Loom', 'value' => 'loom'],
                    ['label' => 'Direct / Raw', 'value' => 'raw'],
                ]],
                ['key' => 'aspectRatio', 'label' => 'Aspect Ratio', 'type' => 'segmented', 'group' => 'style', 'options' => [
                    ['label' => '16:9', 'value' => '16/9'],
                    ['label' => '4:3', 'value' => '4/3'],
                    ['label' => '1:1', 'value' => '1/1'],
                ]],
                ['key' => 'posterUrl', 'label' => 'Thumbnail (optional)', 'type' => 'media'],
                ['key' => 'padding', 'label' => 'Padding (px)', 'type' => 'range', 'min' => 0, 'max' => 150, 'group' => 'style'],
                ['key' => 'backgroundColor', 'label' => 'Background Color', 'type' => 'theme-color', 'group' => 'style', 'compact' => true, 'allowTransparent' => true, 'defaultValue' => 'transparent', 'customDefault' => '#f4f4f5'],
            ],
        ],
        'FAQBlock' => [
            'type' => 'FAQBlock',
            'label' => 'FAQ Accordion',
            'category' => 'content',
            'icon' => 'help-circle',
            'defaultProps' => [
                'items' => [
                    ['question' => 'What is this platform?', 'answer' => 'It is a multitenant website builder.'],
                    ['question' => 'How does pricing work?', 'answer' => 'Check our plans section below.'],
                ],
                'padding' => 20,
                'backgroundColor' => 'transparent',
            ],
            'inspectorFields' => [
                ['key' => 'items', 'label' => 'FAQ Items', 'type' => 'repeater', 'subFields' => [
                    ['key' => 'question', 'label' => 'Question', 'type' => 'text', 'placeholder' => 'Enter question'],
                    ['key' => 'answer', 'label' => 'Answer', 'type' => 'textarea', 'placeholder' => 'Enter answer'],
                ]],
                ['key' => 'padding', 'label' => 'Padding (px)', 'type' => 'range', 'min' => 0, 'max' => 150, 'group' => 'style'],
                ['key' => 'backgroundColor', 'label' => 'Background Color', 'type' => 'theme-color', 'group' => 'style', 'compact' => true, 'allowTransparent' => true, 'defaultValue' => 'transparent', 'customDefault' => '#f4f4f5'],
            ],
        ],
        'TestimonialBlock' => [
            'type' => 'TestimonialBlock',
            'label' => 'Testimonial',
            'category' => 'content',
            'icon' => 'message-square',
            'defaultProps' => [
                'quote' => 'This website builder is incredibly fast and customizable!',
                'authorName' => 'Jane Smith',
                'authorRole' => 'CEO, TechCorp',
                'avatarSrc' => '',
                'padding' => 40,
                'backgroundColor' => 'transparent',
            ],
            'inspectorFields' => [
                ['key' => 'quote', 'label' => 'Quote Text', 'type' => 'textarea', 'placeholder' => 'Enter testimonial quote'],
                ['key' => 'authorName', 'label' => 'Author Name', 'type' => 'text', 'placeholder' => 'Enter name'],
                ['key' => 'authorRole', 'label' => 'Author Role / Company', 'type' => 'text', 'placeholder' => 'Enter role'],
                ['key' => 'avatarSrc', 'label' => 'Avatar Image', 'type' => 'media'],
                ['key' => 'padding', 'label' => 'Padding (px)', 'type' => 'range', 'min' => 0, 'max' => 150, 'group' => 'style'],
                ['key' => 'backgroundColor', 'label' => 'Background Color', 'type' => 'theme-color', 'group' => 'style', 'compact' => true, 'allowTransparent' => true, 'defaultValue' => 'transparent', 'customDefault' => '#f4f4f5'],
            ],
        ],
        'PricingTableBlock' => [
            'type' => 'PricingTableBlock',
            'label' => 'Pricing Cards',
            'category' => 'content',
            'icon' => 'dollar-sign',
            'defaultProps' => [
                'plans' => [
                    [
                        'title' => 'Starter',
                        'price' => '$9',
                        'period' => '/mo',
                        'features' => '1 Website, 5GB Storage, Community Support',
                        'ctaText' => 'Get Started',
                        'ctaUrl' => '#',
                        'isPopular' => false,
                    ],
                    [
                        'title' => 'Professional',
                        'price' => '$29',
                        'period' => '/mo',
                        'features' => '5 Websites, 50GB Storage, Priority Support',
                        'ctaText' => 'Upgrade Now',
                        'ctaUrl' => '#',
                        'isPopular' => true,
                    ],
                ],
                'padding' => 40,
                'backgroundColor' => 'transparent',
            ],
            'inspectorFields' => [
                ['key' => 'plans', 'label' => 'Pricing Plans', 'type' => 'repeater', 'subFields' => [
                    ['key' => 'title', 'label' => 'Plan Title', 'type' => 'text'],
                    ['key' => 'price', 'label' => 'Price (e.g. $29)', 'type' => 'text'],
                    ['key' => 'period', 'label' => 'Period (e.g. /mo)', 'type' => 'text'],
                    ['key' => 'features', 'label' => 'Features (comma-separated)', 'type' => 'text'],
                    ['key' => 'ctaText', 'label' => 'Button Label', 'type' => 'text'],
                    ['key' => 'ctaUrl', 'label' => 'Button Link', 'type' => 'text'],
                    ['key' => 'isPopular', 'label' => 'Popular / Highlighted', 'type' => 'toggle'],
                ]],
                ['key' => 'padding', 'label' => 'Padding (px)', 'type' => 'range', 'min' => 0, 'max' => 150, 'group' => 'style'],
                ['key' => 'backgroundColor', 'label' => 'Background Color', 'type' => 'theme-color', 'group' => 'style', 'compact' => true, 'allowTransparent' => true, 'defaultValue' => 'transparent', 'customDefault' => '#f4f4f5'],
            ],
        ],
        'ContactFormBlock' => [
            'type' => 'ContactFormBlock',
            'label' => 'Contact Form',
            'category' => 'content',
            'icon' => 'mail',
            'defaultProps' => [
                'fields' => [
                    ['type' => 'text', 'label' => 'Your Name', 'placeholder' => 'John Doe', 'required' => 'yes'],
                    ['type' => 'email', 'label' => 'Your Email', 'placeholder' => 'john@example.com', 'required' => 'yes'],
                    ['type' => 'textarea', 'label' => 'Message', 'placeholder' => 'How can we help?', 'required' => 'yes'],
                ],
                'submitLabel' => 'Send Message',
                'successMessage' => 'Thank you! Your message has been sent successfully.',
                'padding' => 40,
                'backgroundColor' => 'transparent',
            ],
            'inspectorFields' => [
                ['key' => 'submitLabel', 'label' => 'Submit Button Text', 'type' => 'text'],
                ['key' => 'successMessage', 'label' => 'Success Message', 'type' => 'textarea'],
                ['key' => 'fields', 'label' => 'Form Fields', 'type' => 'repeater', 'subFields' => [
                    ['key' => 'type', 'label' => 'Field Type', 'type' => 'select', 'options' => [
                        ['label' => 'Text', 'value' => 'text'],
                        ['label' => 'Email', 'value' => 'email'],
                        ['label' => 'Textarea', 'value' => 'textarea'],
                    ]],
                    ['key' => 'label', 'label' => 'Label', 'type' => 'text'],
                    ['key' => 'placeholder', 'label' => 'Placeholder', 'type' => 'text'],
                    ['key' => 'required', 'label' => 'Required', 'type' => 'toggle'],
                ]],
                ['key' => 'padding', 'label' => 'Padding (px)', 'type' => 'range', 'min' => 0, 'max' => 150, 'group' => 'style'],
                ['key' => 'backgroundColor', 'label' => 'Background Color', 'type' => 'theme-color', 'group' => 'style', 'compact' => true, 'allowTransparent' => true, 'defaultValue' => 'transparent', 'customDefault' => '#f4f4f5'],
            ],
        ],
        'AnnouncementBlock' => [
            'type' => 'AnnouncementBlock', 'label' => 'Store Announcement', 'category' => 'content', 'icon' => 'megaphone',
            'defaultProps' => [
                'text' => 'Complimentary delivery on selected orders',
                'barColor' => '--theme-primary',
                'textColor' => '--theme-bg',
                'padding' => 0,
                'backgroundColor' => 'transparent',
            ],
            'inspectorFields' => [
                ['key' => 'text', 'label' => 'Announcement', 'type' => 'text'],
                ['key' => 'barColor', 'label' => 'Bar Color', 'type' => 'theme-color', 'group' => 'style', 'compact' => true, 'defaultValue' => '--theme-primary', 'customDefault' => '#4f46e5'],
                ['key' => 'textColor', 'label' => 'Text Color', 'type' => 'theme-color', 'group' => 'style', 'compact' => true, 'defaultValue' => '--theme-bg', 'customDefault' => '#ffffff'],
            ],
        ],
        'ImageWithTextBlock' => [
            'type' => 'ImageWithTextBlock', 'label' => 'Image with Text', 'category' => 'content', 'icon' => 'panel-left',
            'defaultProps' => ['eyebrow' => 'Our story', 'heading' => 'Made to be lived with', 'body' => 'Add an editorial story about the collection.', 'imageSrc' => '', 'imageAlt' => '', 'imagePosition' => 'left', 'linkLabel' => 'Learn more', 'linkUrl' => '/about', 'padding' => 0, 'backgroundColor' => 'transparent'],
            'inspectorFields' => [
                ['key' => 'eyebrow', 'label' => 'Eyebrow', 'type' => 'text'], ['key' => 'heading', 'label' => 'Heading', 'type' => 'text'], ['key' => 'body', 'label' => 'Body', 'type' => 'textarea'],
                ['key' => 'imageSrc', 'label' => 'Image', 'type' => 'media'], ['key' => 'imageAlt', 'label' => 'Image Alt', 'type' => 'text'],
                ['key' => 'imagePosition', 'label' => 'Image Position', 'type' => 'segmented', 'group' => 'style', 'options' => [['label' => 'Left', 'value' => 'left'], ['label' => 'Right', 'value' => 'right']]],
                ['key' => 'linkLabel', 'label' => 'Link Label', 'type' => 'text'], ['key' => 'linkUrl', 'label' => 'Link URL', 'type' => 'text'],
            ],
        ],
        'CollectionListBlock' => [
            'type' => 'CollectionListBlock', 'label' => 'Collection List', 'category' => 'content', 'icon' => 'gallery-horizontal',
            'defaultProps' => ['eyebrow' => 'Shop by collection', 'heading' => 'Find your everyday favorites', 'bindingVersion' => 1, 'sourceKey' => '', 'collections' => [
                ['title' => 'Home', 'subtitle' => 'Objects for considered rooms', 'imageSrc' => '', 'imageAlt' => '', 'url' => '/shop'],
                ['title' => 'Wear', 'subtitle' => 'Useful pieces made to last', 'imageSrc' => '', 'imageAlt' => '', 'url' => '/shop'],
                ['title' => 'Gift', 'subtitle' => 'Thoughtful finds for giving', 'imageSrc' => '', 'imageAlt' => '', 'url' => '/shop'],
            ], 'padding' => 40, 'backgroundColor' => 'transparent'],
            'inspectorFields' => [['key' => 'eyebrow', 'label' => 'Eyebrow', 'type' => 'text'], ['key' => 'heading', 'label' => 'Heading', 'type' => 'text'], ['key' => 'sourceKey', 'label' => 'Collection Source', 'type' => 'text'], ['key' => 'collections', 'label' => 'Collections', 'type' => 'repeater', 'subFields' => [
                ['key' => 'title', 'label' => 'Title', 'type' => 'text'], ['key' => 'subtitle', 'label' => 'Subtitle', 'type' => 'text'], ['key' => 'imageSrc', 'label' => 'Image', 'type' => 'media'], ['key' => 'imageAlt', 'label' => 'Image Alt', 'type' => 'text'], ['key' => 'url', 'label' => 'URL', 'type' => 'text'],
            ]]],
        ],
        'ProductGridBlock' => [
            'type' => 'ProductGridBlock', 'label' => 'Product Grid', 'category' => 'content', 'icon' => 'shopping-bag',
            'defaultProps' => [
                'eyebrow' => 'Curated selection',
                'heading' => 'The current edit',
                'bindingVersion' => 1,
                'sourceKey' => 'featured',
                'sort' => 'featured',
                'limit' => 12,
                'editingMode' => 'simple',
                'layoutType' => 'grid',
                'desktopColumns' => 4,
                'tabletColumns' => 2,
                'mobileColumns' => 1,
                'columns' => 4,
                'gap' => 24,
                'alignment' => 'left',
                'imageRatio' => 'portrait',
                'tabletImageRatio' => 'portrait',
                'mobileImageRatio' => 'portrait',
                'cardPreset' => 'minimal',
                'cardSurface' => 'transparent',
                'cardBorder' => 'none',
                'cardShadow' => 'none',
                'cardCorners' => 'none',
                'cardPadding' => 0,
                'cardSpacing' => 10,
                'hoverEffect' => 'fade',
                'buttonStyle' => 'primary',
                'buttonLabel' => 'Add to cart',
                'showBadge' => 'yes',
                'showComparePrice' => 'yes',
                'cardContent' => [
                    ['key' => 'image', 'label' => 'Product image', 'visible' => true],
                    ['key' => 'category', 'label' => 'Category', 'visible' => false],
                    ['key' => 'name', 'label' => 'Product name', 'visible' => true],
                    ['key' => 'price', 'label' => 'Price', 'visible' => true],
                    ['key' => 'description', 'label' => 'Description', 'visible' => false],
                    ['key' => 'availability', 'label' => 'Availability', 'visible' => true],
                    ['key' => 'button', 'label' => 'Add to cart', 'visible' => false],
                ],
                'showControls' => 'no',
                'paginationEnabled' => 'no',
                'pageSize' => 4,
                'viewAllLabel' => 'View all',
                'viewAllUrl' => '/shop',
                'products' => [
                    ['key' => 'linen-throw', 'title' => 'Linen throw', 'priceLabel' => '$48.00', 'compareAtLabel' => '', 'badge' => 'New', 'imageSrc' => '', 'imageAlt' => '', 'url' => '#'],
                    ['key' => 'stoneware-cup', 'title' => 'Stoneware cup', 'priceLabel' => '$24.00', 'compareAtLabel' => '', 'badge' => '', 'imageSrc' => '', 'imageAlt' => '', 'url' => '#'],
                    ['key' => 'canvas-tote', 'title' => 'Canvas tote', 'priceLabel' => '$36.00', 'compareAtLabel' => '', 'badge' => '', 'imageSrc' => '', 'imageAlt' => '', 'url' => '#'],
                    ['key' => 'cedar-candle', 'title' => 'Cedar candle', 'priceLabel' => '$32.00', 'compareAtLabel' => '$40.00', 'badge' => 'Sale', 'imageSrc' => '', 'imageAlt' => '', 'url' => '#'],
                ],
                'padding' => 40,
                'backgroundColor' => 'transparent',
            ],
            'inspectorFields' => [],
        ],
        'ProductDetailBlock' => [
            'type' => 'ProductDetailBlock', 'label' => 'Product Detail', 'category' => 'interactive', 'icon' => 'package',
            'defaultProps' => ['bindingVersion' => 1, 'sourceKey' => '', 'vendor' => 'Independent maker', 'title' => 'Linen throw', 'priceLabel' => '$48.00', 'description' => 'A tactile everyday layer made with considered materials.', 'options' => ['Natural', 'Charcoal'], 'images' => [['src' => '', 'alt' => 'Product image'], ['src' => '', 'alt' => 'Product detail']], 'buttonLabel' => 'Add to cart', 'meta' => 'Taxes and shipping are calculated by the connected store.', 'padding' => 40, 'backgroundColor' => 'transparent'],
            'inspectorFields' => [['key' => 'sourceKey', 'label' => 'Product Source', 'type' => 'text'], ['key' => 'vendor', 'label' => 'Vendor', 'type' => 'text'], ['key' => 'title', 'label' => 'Title', 'type' => 'text'], ['key' => 'priceLabel', 'label' => 'Price', 'type' => 'text'], ['key' => 'description', 'label' => 'Description', 'type' => 'textarea'], ['key' => 'buttonLabel', 'label' => 'Button Label', 'type' => 'text'], ['key' => 'meta', 'label' => 'Supporting Text', 'type' => 'text'], ['key' => 'images', 'label' => 'Images', 'type' => 'repeater', 'subFields' => [['key' => 'src', 'label' => 'Image', 'type' => 'media'], ['key' => 'alt', 'label' => 'Alt', 'type' => 'text']]]],
        ],
        'CartBlock' => [
            'type' => 'CartBlock', 'label' => 'Shopping Cart', 'category' => 'interactive', 'icon' => 'shopping-cart',
            'defaultProps' => ['eyebrow' => 'Your selection', 'heading' => 'Shopping bag', 'body' => 'Review your items before continuing to checkout.', 'emptyHeading' => 'Your bag is empty', 'emptyBody' => 'Explore the current collection and find something considered.', 'continueUrl' => '/shop', 'checkoutLabel' => 'Continue to checkout', 'padding' => 40, 'backgroundColor' => 'transparent'],
            'inspectorFields' => [['key' => 'eyebrow', 'label' => 'Eyebrow', 'type' => 'text'], ['key' => 'heading', 'label' => 'Heading', 'type' => 'text'], ['key' => 'body', 'label' => 'Body', 'type' => 'textarea'], ['key' => 'emptyHeading', 'label' => 'Empty Cart Heading', 'type' => 'text'], ['key' => 'emptyBody', 'label' => 'Empty Cart Body', 'type' => 'textarea'], ['key' => 'continueUrl', 'label' => 'Continue Shopping URL', 'type' => 'text'], ['key' => 'checkoutLabel', 'label' => 'Checkout Label', 'type' => 'text']],
        ],
        'NewsletterBlock' => [
            'type' => 'NewsletterBlock', 'label' => 'Store Newsletter', 'category' => 'interactive', 'icon' => 'send',
            'defaultProps' => ['eyebrow' => 'Stay in touch', 'heading' => 'Notes from the shop', 'body' => 'New collections and thoughtful stories, occasionally.', 'placeholder' => 'Email address', 'buttonLabel' => 'Subscribe', 'padding' => 0, 'backgroundColor' => 'transparent'],
            'inspectorFields' => [['key' => 'eyebrow', 'label' => 'Eyebrow', 'type' => 'text'], ['key' => 'heading', 'label' => 'Heading', 'type' => 'text'], ['key' => 'body', 'label' => 'Body', 'type' => 'textarea'], ['key' => 'placeholder', 'label' => 'Placeholder', 'type' => 'text'], ['key' => 'buttonLabel', 'label' => 'Button Label', 'type' => 'text']],
        ],
        'TrustValuesBlock' => [
            'type' => 'TrustValuesBlock', 'label' => 'Store Values', 'category' => 'content', 'icon' => 'shield-check',
            'defaultProps' => ['items' => [['title' => 'Considered sourcing', 'body' => 'Materials and makers selected with care.'], ['title' => 'Personal service', 'body' => 'Helpful guidance from real people.'], ['title' => 'Secure checkout', 'body' => 'Purchasing is handled by your connected store.']], 'padding' => 40, 'backgroundColor' => 'transparent'],
            'inspectorFields' => [['key' => 'items', 'label' => 'Values', 'type' => 'repeater', 'subFields' => [['key' => 'title', 'label' => 'Title', 'type' => 'text'], ['key' => 'body', 'label' => 'Body', 'type' => 'textarea']]]],
        ],
        'MenuBlock' => [
            'type' => 'MenuBlock',
            'label' => 'Menu',
            'category' => 'content',
            'icon' => 'utensils',
            'defaultProps' => [
                'heading' => 'Our Menu',
                'subheading' => 'Freshly prepared, served with care',
                'columns' => 2,
                'items' => [
                    ['category' => 'Starters', 'name' => 'Heirloom Tomato Salad', 'description' => 'Basil, aged balsamic, sea salt.', 'price' => '$12'],
                    ['category' => 'Starters', 'name' => 'Charred Sourdough', 'description' => 'Cultured butter, rosemary.', 'price' => '$8'],
                    ['category' => 'Mains', 'name' => 'Wood-Fired Ribeye', 'description' => 'Roasted garlic, seasonal greens.', 'price' => '$34'],
                    ['category' => 'Mains', 'name' => 'Handmade Pappardelle', 'description' => 'Slow-braised ragù, pecorino.', 'price' => '$24'],
                    ['category' => 'Desserts', 'name' => 'Dark Chocolate Tart', 'description' => 'Sea salt, crème fraîche.', 'price' => '$11'],
                ],
                'padding' => 40,
                'backgroundColor' => 'transparent',
            ],
            'inspectorFields' => [
                ['key' => 'heading', 'label' => 'Heading', 'type' => 'text', 'placeholder' => 'Our Menu'],
                ['key' => 'subheading', 'label' => 'Subheading', 'type' => 'text', 'placeholder' => 'Freshly prepared'],
                ['key' => 'columns', 'label' => 'Columns', 'type' => 'columns', 'group' => 'style', 'options' => [
                    ['label' => '1', 'value' => 1],
                    ['label' => '2', 'value' => 2],
                    ['label' => '3', 'value' => 3],
                ]],
                ['key' => 'items', 'label' => 'Menu Items', 'type' => 'repeater', 'subFields' => [
                    ['key' => 'category', 'label' => 'Category', 'type' => 'text', 'placeholder' => 'Starters'],
                    ['key' => 'name', 'label' => 'Name', 'type' => 'text', 'placeholder' => 'Dish name'],
                    ['key' => 'description', 'label' => 'Description', 'type' => 'textarea', 'placeholder' => 'Short description'],
                    ['key' => 'price', 'label' => 'Price', 'type' => 'text', 'placeholder' => '$0'],
                ]],
                ['key' => 'padding', 'label' => 'Padding (px)', 'type' => 'range', 'min' => 0, 'max' => 150, 'group' => 'style'],
                ['key' => 'backgroundColor', 'label' => 'Background Color', 'type' => 'theme-color', 'group' => 'style', 'compact' => true, 'allowTransparent' => true, 'defaultValue' => 'transparent', 'customDefault' => '#f4f4f5'],
            ],
        ],
    ],
    'nesting' => [
        'SectionBlock' => [
            'HeroBlock', 'FeatureBlock', 'LayoutGrid', 'LayoutColumn', 'AtomicText', 'ButtonBlock', 'DividerBlock', 'SpacerBlock', 'ImageBlock',
            'RichTextBlock', 'VideoEmbedBlock', 'FAQBlock', 'TestimonialBlock', 'PricingTableBlock', 'ContactFormBlock',
            'AnnouncementBlock', 'ImageWithTextBlock', 'CollectionListBlock', 'ProductGridBlock', 'ProductDetailBlock', 'CartBlock', 'NewsletterBlock', 'TrustValuesBlock', 'MenuBlock',
        ],
        'LayoutGrid' => [
            'HeroBlock', 'FeatureBlock', 'LayoutGrid', 'LayoutColumn', 'AtomicText', 'ButtonBlock', 'DividerBlock', 'SpacerBlock', 'ImageBlock',
            'RichTextBlock', 'VideoEmbedBlock', 'FAQBlock', 'TestimonialBlock', 'PricingTableBlock', 'ContactFormBlock',
            'AnnouncementBlock', 'ImageWithTextBlock', 'CollectionListBlock', 'ProductGridBlock', 'ProductDetailBlock', 'CartBlock', 'NewsletterBlock', 'TrustValuesBlock', 'MenuBlock',
        ],
        'LayoutColumn' => [
            'HeroBlock', 'FeatureBlock', 'LayoutGrid', 'LayoutColumn', 'AtomicText', 'ButtonBlock', 'DividerBlock', 'SpacerBlock', 'ImageBlock',
            'RichTextBlock', 'VideoEmbedBlock', 'FAQBlock', 'TestimonialBlock', 'PricingTableBlock', 'ContactFormBlock',
            'AnnouncementBlock', 'ImageWithTextBlock', 'CollectionListBlock', 'ProductGridBlock', 'ProductDetailBlock', 'CartBlock', 'NewsletterBlock', 'TrustValuesBlock', 'MenuBlock',
        ],
    ],
];
